openapi: 3.0.0
info:
  title: Landfills Detection Service
  version: 1.0.0

paths:
  /detections:
    get:
      tags:
        - landfills
      summary: Retrieve all detected landfills
      description: Get a list of all landfills detected, with optional filtering by municipality.
      parameters:
        - name: municipality
          in: query
          description: Municipality ID to filter landfills.
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: A list of detected landfills.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Landfill"
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - landfills
      summary: Add a new landfill
      description: Submit a new landfill detection record.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewLandfillRequest"
      responses:
        "200":
          description: Landfill successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Landfill"
        "400":
          description: Invalid request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /detections/{id}:
    get:
      tags:
        - landfills
      summary: Retrieve landfill details
      description: Get detailed information about a specific landfill, including its location as a polygon (for SAT) or point (for SIG).
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the landfill to retrieve.
          schema:
            type: integer
      responses:
        "200":
          description: Landfill details along with its geometry information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Landfill"
        "404":
          description: No event found with this ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - landfills
      summary: Update landfill validity
      description: Update the validity status of a specific landfill (VALID, INVALID, or UNKNOWN).
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the landfill to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/DetectionValidity"
              required:
                - status
      responses:
        "200":
          description: Landfill status updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Landfill"
        "400":
          description: Invalid request body or landfill ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Landfill not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    DetectionValidity:
      type: string
      enum:
        - VALID
        - INVALID
        - UNKNOWN

    Geometry:
      oneOf:
        - type: object
          description: Geometry of detected landfills (Polygon)
          properties:
            type:
              type: string
              example: MultiPolygon
            coordinates:
              type: array
              description: Coordinates of the polygon
              items:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    example: 45.12345
          required:
            - type
            - coordinates
        - type: object
          description: Point representing a signaled landfill (Point)
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              description: Coordinates of the point
              items:
                type: number
                example: 45.12345
          required:
            - type
            - coordinates

    Landfill:
      type: object
      properties:
        id:
          type: integer
          example: 1
        detected_from:
          type: string
          description: Detection type.
          example: aerial
        detection_time:
          type: string
          format: date-time
          description: Time when the landfill was detected.
          example: "2023-10-13T12:00:00Z"
        municipality_id:
          type: integer
          description: ID of the municipality.
          example: 1001
        confidence:
          type: number
          description: The confidence of the detection (normalized between 0 and 1).
          example: 0.85
        status:
          $ref: "#/components/schemas/DetectionValidity"
        imageURI:
          type: string
        geometry:
          $ref: "#/components/schemas/Geometry"
      required:
        - id
        - municipality_id
        - geometry
        - status

    NewLandfillRequest:
      type: object
      properties:
        municipality_id:
          type: integer
          description: ID of the municipality.
          example: 1001
        detected_from:
          type: string
          description: Detection type.
          example: aerial
        detection_time:
          type: string
          format: date-time
          description: Time when the landfill was detected.
          example: "2023-10-13T12:00:00Z"
        confidence:
          type: number
          description: The confidence of the detection (normalized between 0 and 1).
          example: 0.85
        imageURI:
          type: string
        geometry:
          $ref: "#/components/schemas/Geometry"
      required:
        - municipality_id
        - detected_from
        - detection_time
        - confidence
        - geometry
        - imageURI

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Invalid landfill ID."
        id:
          type: string
          example: "123"
          description: "ID of the landfill (if applicable)."
        details:
          type: object
          description: "Additional error details."
