env: dev

landfill:
  dataset_folder_name: landfill

network:
  vpc_prefix_tag: "rfa-labs"

storage:
  datasets_efs_tagname: "utils-dev-dacoms-persistence-dataset-filesystem"

utils:
  feature_flags:
    notebook_eraser_flag: false
